"""Add sentence_embeddings table

Revision ID: efa803e38faa
Revises: c923c71ebb9d
Create Date: 2025-09-03 12:06:53.429056

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = 'efa803e38faa'
down_revision = 'c923c71ebb9d'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'sentence_embeddings',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('content', sa.Text, nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.Vector(1536), nullable=False),
    )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentence_embeddings')
    # ### end Alembic commands ###
