"""Remove id column, set product_id as primary key

Revision ID: 4209f2422165
Revises: 59da043a30bd
Create Date: 2025-08-20 18:15:35.725301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4209f2422165'
down_revision = '59da043a30bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('products_product_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('products_product_id_key'), ['product_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
