"""Add a role field to User

Revision ID: 8e006cceca3e
Revises: 56dcde7b2bf4
Create Date: 2025-08-28 10:58:28.990963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e006cceca3e'
down_revision = '56dcde7b2bf4'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add the column as nullable first
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # Set default value for existing users
    op.execute("UPDATE users SET role='staff' WHERE role IS NULL")

    with op.batch_alter_table('users', schema=None) as batch_op:
        # Now alter the column to be NOT NULL
        batch_op.alter_column('role', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
